# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - cp-win-dotnet

on:
  push:
    branches: main
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: e160ca65-836f-4be6-8ef5-e6234b90de87   # set this to your Azure Subscription Id
  AZURE_RESOURCE_GROUP: function-app-storage-private-endpoints   # set this to your Azure Resource group's name  
  FUNCTION_APP: func-h4lz5w7bfnvhe # set this to your Azure Function app's name  
  STORAGE_ACCOUNT: nameforstorageacct  # Does not have to exist, public storage will be created for deployment
  CONTAINER: nameforstoragecontainer # name for a temporary container needed for deployment
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
        
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
          
      - name: Zip the app contents
        uses: papeloto/action-zip@v1
        with:
          files: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
          dest: app.zip

      - name: 'Az Commands to Create Storage for Deployment'
        shell: pwsh
        run: |
            az storage account create -n ${{ env.STORAGE_ACCOUNT }} -g ${{ env.AZURE_RESOURCE_GROUP }} --allow-blob-public-access true
            az storage container create -n ${{ env.CONTAINER }} --account-name ${{ env.STORAGE_ACCOUNT }} --public-access blob
            az storage blob upload -f app.zip --account-name ${{ env.STORAGE_ACCOUNT }} -c ${{ env.CONTAINER }} -n package.zip --overwrite true
            
      - name: 'Az Command for Deployment with ARM Template'
        shell: pwsh
        run: |
            $Env:Expiry=(get-date).AddMinutes(30).ToString("yyyy-MM-ddTHH:mm:ssZ")
            $Env:ZIP_URL=$(az storage blob generate-sas --full-uri --permissions r --expiry $Env:Expiry --account-name ${{ env.STORAGE_ACCOUNT }} -c ${{ env.CONTAINER }} -n package.zip)
            az deployment group create --name deploy --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --template-file azuredeploy.json --parameters functionAppName='${{ env.FUNCTION_APP }}' packageUri=$Env:ZIP_URL 
            
      - name: 'Az Commands to Delete Temporary Container'
        shell: pwsh
        run: |
            az storage container delete -n ${{ env.CONTAINER }} --account-name ${{ env.STORAGE_ACCOUNT }} 
